### PR TITLE
Add Crowbar's idle anims, Python's reload sound, Merge @DanielOaks commit for Mac OSX 10.9 compile and Perforce and Linux's Makefile VALVE_TOOLS and PERFORCE conditions

### PR DESCRIPTION
**Pull request by JoelTroch**
First of all, sorry to make a huge PR, I tried to seperate the work to make multiple little PRs but it ends up with more mess.

This PR adds :
* Crowbar's idle animations (see issue #1585).
* Python's reload sound (see issue #1585).
* Merge commit of @DanielOaks for Mac OSX 10.9 compile support and optional use of Perforce.
* [Linux] VALVE_TOOLS condition, if set to TRUE, uses Valve's GCC/G++ compilers. Otherwise, uses "standard" GCC/G++ compilers.
* [Linux] PERFORCE condition, if set to TRUE, uses Perforce. Otherwise, don't.

For any questions, remarks, feel free to ask.

And sorry for the "commits mess" on issue #1585, I need to clean my local work on my fork one of these days.

### CODE REVIEW

**Comment by tschumann** [comment]
Why did you close this?

**Comment by JoelTroch** [comment]
@tschumann Closed because my fork became a huge mess (I'm not an expert in Git) and my PRs also contains others PRs and stuff were wrong, will make a new clean PR when I have time.

**Comment by DanielOaks** [comment]
Just a note @JoelTroch, for the changes where you make fixes to the
PERFORCE condition and add the VALVE_TOOLS env variable, you can PR my
branch with those changes if you'd like. May make more sense to try and
have all those build changes rolled into a single PR :)

**Comment by DanielOaks** [comment]
Oh, my mistake, you already commented about that in my PR.

If you'd like to create a new branch with just those changes in it, and
either send a PR to my branch or make another comment on my PR, I should be
able to pull those into my branch.

**Comment by JoelTroch** [comment]
@DanielOaks : Will do that once I have time ^_^

**Pull request closed without merging**
