### PR TITLE
Input code fixes

### PR DESCRIPTION
**Pull request by dtugend**
Fixes ValveSoftware/halflife#1546
- fixed m_rawinput 1 mouse trapped inside a rectangle
- fixed thirdperson camera not working as it should

Fixes ValveSoftware/halflife#1558
- recoded mousethread and made it somewhat useful for very fast mouse
  movements (will reset CursorPos now) and thus also fixed some thread
  synchronization issues (hopefully)

Further fixes:
- Fixed IN_JoyMove doing nothing on Linux for ricochet client
- Limited mouse thread sleep to sane values between 0 and 1000

Does not fix the following:
- Original mouse button down/up reacting when scoreboard mouse is on bugs.

### CODE REVIEW

**Comment by JoelTroch** [comment]
Made a quick test on a clean SDK, nothing wrong to report. Great job !

**Comment by ripieces** [comment]
Thanks, always good to have someone else test it or look through the code.

I am mostly worried about making mistakes in thread synchronization on Windows builds (with -mousethread launch option and m_rawinput 0), but I hope I didn't introduce new ones and fixed the old ones.

PS:

The reason why I coded InterlockedExchange* variable access despite using a lock mechanism is because the Windows Documentation didn't say anything about how the memory barrier works for the functions WaitForSingleObject and SetEvent (i.e. I can't know from the documentation if it affects all memory access or only interlocked memory access).

The InterlockedExchange functions used in the code make sure there is a memory barrier (which is a lot more than just declaring a variable as volatile does).

I used volatile for the mouse_thread_sleep variable though, because I thought the side effects don't matter there (the user might only observer a very small additional random delay until the changes in that variable are applied to the thread).

PPS:
If anyone would find some good documentation how the memory barrier works in WaitForSingleObject and SetEvent and how to use memory barriers in Visual C++ 2010 properly, that would be cool if I could have it for reading.
(Since I am not sure if the memory-barrier on hardware-level probably  caused by WaitForSingleObject and SetEvent and C++ sequence points and volatile variable access alone are guaranteed to already avoid things like Out-Of-Order execution - That is why is used InterlockedExchange* Functions additionally to the WaitForSingleObject / SetEvent functions.)

**Comment by ripieces** [comment]
Okay I found a problem, which is not a problem yet, but will become one as soon as someone uses ISO C++ 11:

The
```
static volatile cvar_t * someName;
````
would work fine in Visual Studio 2010 and lots of earlier versions, however it might not work in ISO C++ 11 anymore, because the struct cannote be copied in one instruction:
http://msdn.microsoft.com/en-us/library/12a04hfd%28v=vs.120%29.aspx

A possible solution would be to instead make the access on the float value volatile:
```
int sleepVal = (int)*(volatile float *)&m_mousethread_sleep->value;
```

But that still would be not standard conform, because the ISO C++ 11 standard says:
The volatile keyword in C++11 ISO Standard code is to be used only for hardware access; **do not use it for inter-thread communication**. For inter-thread communication, use mechanisms such as std::atomic<T> from the C++ Standard Template Library.

I am very confused now.

Anyone an idea?

**Comment by ripieces** [comment]
Okay, fixed it (see commit above).
Fix may not seem elegant, I went for stability.

**Comment by ripieces** [comment]
Okay fixed it, see commit above.
Fix is not that elegant, but should be stable.

**Comment by YaLTeR** [comment]
Fix for mouse disappearing on tabbing out/back into the game: https://github.com/YaLTeR/OpenAG/commit/8e60ac3e22a27b48a5be384f70e4d01773cd3cbb

**Pull request closed without merging**
