### PR TITLE
Fixed several utilities, added VS2013 & VS 2015 support...

### PR DESCRIPTION
**Pull request by malortie**
_Fixed_:
- Several utilities,  <17 / 19> builable projects. Projects **serverctrl** & **smdexp** cannot compile due to missing dependencies such as headers/libraries. .i.e [MFC](http://en.wikipedia.org/wiki/Microsoft_Foundation_Class_Library). 

- Replaced glaux with ~~freeglut~~ [SDL2](https://www.libsdl.org/index.php). Projects that use **gldraw.c**, such as **qcsg**, **qbsp2**, **qrad** now use ~~freeglut~~ **SDL2**, which is provided in this commit. ~~See folders: libs/public/freeglut; external/freeglut~~.

_Added_:
- [Chumbalum Soft's model viewer 1.25](http://www.milkshape3d.com/) as a project in *utils* solution, **utils.sln**, which, at this time, is only supported on *Windows OS*.

- [ZHLT](http://zhlt.info/) tools, along with **zhlt** solution, **zhlt.sln**.

- **everything.sln**, which contains all projects found in both projects.sln & utils.sln solutions.

- *VS2013* & *VS2015* support for all fixed & added projects.

[Link to new branch](https://github.com/malortie/halflife/tree/branch-malortie-02).

### CODE REVIEW

**Comment by JoelTroch** [comment]
This looks good, nice work ^_^

However IMO, I think it would be better to not disable any warning and let the user (programmer) disable them if he want to.

**Comment by malortie** [comment]
@JoelTroch  
 
> I think it would be better to not disable any warning and let the user (programmer) disable them if he want to.  

I will handle these when I will have enough spare time, as I have personal matter to attend to. 

In the interim, I encourage you, along with others interested with these features & additions, to list what they would like to see added or improved, so that I can update the current pull request.

**Comment by ripieces** [comment]
Firstly thank you for your work @malortie .

I **very strongly concur** with @JoelTroch that it's better to not disable warnings (except for the CRT secure warnings). I prefer adjusting the code properly to make them go away, since most warnings are there for a reason.

I think it would be better to port a share of the utils to SDL2, instead of using freeglut, which I partially had done already on my local copy a while ago (but have deleted by now, see next sentence for reason).
But I asked @alfred-valve  if it makes sense and he said s.th. like that it's beyond the scope of this repository (if I remember correctly). But if Alfred would change his mind about that, then I would like to see them ported to SDL2 :-)

Apart from that I am not a huge fan of checking executable binary files into a repository, if it can be avoided. (Yeah I know, there are already a few, to name them the VGUI binaries (which is because they are closed source) and the SDL2 binaries (which is probably because they wanted to make sure we really use the same version as them - or I dunno).

**Comment by malortie** [comment]
@ripieces 

> Firstly thank you for your work

You are welcome. Glad to lend a hand.

> @ripieces  
it's better to not disable warnings (except for the CRT secure warnings). I prefer adjusting the code properly to make them go away, since most warnings are there for a reason.  

I agree, along with @JoelTroch, that fixing the source code would represent a more convenient alternative than disabling these.

> Apart from that I am not a huge fan of checking executable binary files into a repository, if it can be avoided. (Yeah I know, there are already a few, to name them the VGUI binaries (which is because they are closed source) and the SDL2 binaries (which is probably because they wanted to make sure we really use the same version as them - or I dunno).  

I mostly agree, as SteamPipe version of the game might use additional interfaces which are not present in older version of this source code, .i.e Half-Life SDK v 2.3, etc. Therefore, using SDL provided in this repository as a base for the utilities can help minimize dependency compatibility issues and other side problems such as linkage errors.

The reason freeglut was chosen as the base for OpenGL dependent utilities in this pull request was to avoid modifying too much of their code, as using SDL would require a considerable, if not complete rewrite & structure of these.

I changed the [default branch](https://github.com/malortie/halflife/tree/master) of my repository to [the same as this pull request](https://github.com/malortie/halflife/tree/branch-malortie-01). Until I can find more spare time, anyone is welcomed to try and contribute. In the events of a fix, simply do send a pull request so that I may merge it with this one.

**Comment by malortie** [comment]
@ripieces

At your request, I managed to port glaux dependent related projects such as mdlviewer,**qcfg**, **qbsp** to [SDL2](https://www.libsdl.org/index.php).

I also created **zhlt.sln** and added  [ZHLT](http://zhlt.info/) projects:
- *hlbsp* ≈ qbsp2
- *hlcsg* ≈ qcsg
- *hlrad* ≈ qbsp2
- *hlvis* ≈ vis
- *ripent*

These projects are also added to both **utils.sln** & **everything.sln**, respectfully with support for both **VS2013** & **VS2015**.

I managed to test newly compiled **ZHLT** tools with [Valve Hammer Editor 3.4](https://en.wikipedia.org/wiki/Valve_Hammer_Editor) and it seems to work. Although, many more tests would still be required to ensure proper stability, Therefore, I encourage interested people who wish to contribute, to test these and provide report, along with map samples.

@JoelTroch

The next issue I will probably attend to is to fix source code in order to prevent deprecation warnings, aside from CRT functions, as mentioned earlier.

In the meantime, I created a [new branch](https://github.com/malortie/halflife/tree/branch-malortie-02) which contains the new additions listed above.

**Comment by ripieces** [comment]
@malortie Thank you for your work.

I don't want to get you mad, so I am not sure if I should stop commenting on this, but I think I will comment:

1) The changes you edited into the first post of this pull request are limited to the new branch you made and not in this pull request, since it's limited to the branch you submitted it with.

I examined your new branch (not in this pull request):

1) Thank you for upgrading to SDL2 instead, I think it's a good idea, but not sure if @alfred-valve will like it, for the reasons I mentioned earlier.

1b) Problem with 1) is that old Project files (MSVC 6.0 / 2010) would need to be updated in order to still compile with your new changes - or removed. My personal problem is that I still use a Windows XP system in order to compile for Windows, meaning I can not test 2013/2015. But if most others are okay with that I vote for removing support of 6.0 and 2010 - I mean it's my own fault, that I am using such an old system :-( If they think it should stay, then I could try to update the 6.0 / 2010 project files to match your 2013/2015 ones when I have gotten time.

2) Still a lot of binary files in that branch, it even got at least one more (hlmv.exe if I remember correctly), is that really necessary? Maybe you forgot to remove them, for example you forgot to remove the now in that branch unused freeglut library source and binaries.

3) You are combining very many changes into a single pull request (I made that mistake too with my Input code fixes pull request, but I am not sure if I could have split it better) - while most of them are useful that makes it harder to handle the pull requests and also increases the likelihood for it to be rejected. A possible solution to this might be to split the addition of the third party tools (ZHLT and modelviewer) into a separate branch and make that for a separate pull requests (just to make sure if they don't want these additions, they still have the possibility to accept your other improvements). 

What I suggest is one branch / pull request for updating to 2013/2015 + SDL2 in tools and one branch / pull request for the 3rd party tool introduction. In case you decide to make a new pull request / branch for both, then you could also make the commit history more pretty (no addition + remove of freeglut etc). But you can also use the current branch and remove what doesn't belong in there (but then the history wouldn't be pretty, not sure if you care a lot about that).


Please see my reply only as feedback and as my personal thoughts, in the end it's your pull request(s) and up to you what you submit there.
As said above I can't help much with the 2013/2015 testing at the moment, because of my old Windows XP. I can only help with testing if MSVC6.0/2010 still compile the projects and adjusting them where possible and required. Please let me know when I shall do that, when you got your pull request in a somewhat polished state where it makes sense and I will try then when I have time.

**Comment by ripieces** [comment]
Btw, one more thing for future updates: While I like to make code more pretty too (adjusting indents, spaces etc.), it's only a good idea at places where you actually change s.th., otherwise it's needlessly increasing the number of changes.

(Yes I know there is one commit only for fixing line endings in this repository (which unluckily is by me), which caused to be counted as a lot of changes, but that was required in order to get the repository consistent for Linux & Windows developers & downloads (.zip) with their default crlf GIT settings.)

Please again see that only as suggestion, for which you have the right to ignore it :-)

**Comment by malortie** [comment]
@ripieces

At first, should I thank you for all your constructive criticisms. 

After reading your report multiple times and looking at the branches I made earlier, I see tremendous great points & arguments. I can assure you that I am fully aware of these criticisms are being suggestions, and this is why I am interested in hearing more, as suggestions/responses are possibly, if not the best way to improve work quality.

As for the main points covered in your response,

> **1)**  
> not sure if @alfred-valve will like it, for the reasons I mentioned earlier.

You are right, according to  @alfred-valve, this is considered to be beyond the project's scope. Also, looking at his latest activity, I am not sure if he may or not handle requests in the near future. Therefore, I will leave the SDL2 port on another branch until we get a proper confirmation.

>**1b)**  
> I still use a Windows XP system in order to compile for Windows, meaning I can not test 2013/2015

Since several users are still using Windows XP to build the tools, I understand why there were many requests requiring VS2010. In this case, I will try and see if I can create proper support for VS2010.

> **2)**  
> Still a lot of binary files in that branch, it even got at least one more (hlmv.exe if I remember correctly)

Correct, a complete cleanup will be required. As for **hlmv.exe**, this file was part of the source code archive from which [Chumbalum soft](http://www.milkshape3d.com/)'s model viewer was packed with, and I thought it only fair to be included, as this was part of the original distribution. Of course, there are many good points for not committing any binary files, and this is why it should be removed. Before doing so, I would require a bit more opinions from other users on that matter.

> **3)** 
> - You are combining very many changes into a single pull request...
- while most of them are useful, that makes it harder to handle the pull requests and also increases the likelihood for it to be rejected...
- A possible solution to this might be to split the addition of the third party tools...

Since I am quite new to GitHub and in general, to version control, I wanted to make sure to handle requests and make changes, without creating multiple pull requests (avoid pull request overload). 
To create multiple branches seems to be a convenient approach, in contrast to singular ones.

> I can only help with testing if MSVC6.0/2010 still compile the projects and adjusting them where possible and required. ... when you got your pull request in a somewhat polished state...

I will do my best to clean the current branches and see about creating more structured pull requests from now on. Along with you and others, I understand that this is not always easy to work with, as the current game source code is cluttered & coupled, if you ask me. Looking at **dmc**, **hl**, **ricochet** projects, several functions/instructions are duplicated, could be refactorized. Particulars interests I have, are code sharing across projects, along with better documentation, since this would reduce complexity, making logic errors/bugs less hard to spot, and improve maintainability.

I am glad that you, as well as @JoelTroch, are taking time to write these words; thoughts; suggestions on how to improve pull requests. Constructive criticisms are always welcomed. I hope, when I will be able to find spare time, to be able to create more structured solution, as suggested in **_3)_**.

I will leave the current pull request opened, in the case other people might have additional requests to be incorporated, but please keep in mind that once new pull requests that will contain separate improvements will be finalized, it will be closed.

You can find my most recent branch [here](https://github.com/malortie/halflife/tree/branch-malortie-02).

**Comment by JoelTroch** [comment]
One thing that I "disapprove" (and maybe Valve will) is the fact that you uploaded ZHLT's source code, here are the reasons:
* Most of the modders know that Valve's compilers (QCSG, QBSP, QVIS, QRAD) are "outdated" and ZHLT have been heavily improved and became the "standard" when compiling maps. If the modder wants really wants to be "oldschool", he will be using Valve's compilers, otherwise, it will likely be ZHLT or one of it's forks.
* Yes, there are multiple forks of ZHLT and therefore it's up to the modder to choose between Valve's compilers, ZHLT, SHLT Vluzacn's ZHLT or any other fork if available. The source codes of the original and the forks can be eaily downloaded.

**Comment by malortie** [comment]
@JoelTroch

Thanks for the feedback.

 > Yes, there are multiple forks of ZHLT ... ZHLT, SHLT Vluzacn's ZHLT or any other fork if available...

When I will get around doing what was mentioned previously, I'll be certain to have a look at those, as I wasn't really aware of already existing repositories.

Thank you.

**Pull request closed without merging**
